# Generated by Django 4.2.2 on 2023-06-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_type',
            field=models.CharField(choices=[('C', 'Vêtement'), ('A', 'Accessoire')], default='', max_length=1),
        ),
    ]
