# Generated by Django 4.2.2 on 2023-06-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default='', max_length=1),
        ),
    ]
