# Generated by Django 4.2.2 on 2023-06-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('O', 'Autre')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='product_type',
            field=models.CharField(choices=[('Y', 'Accessoires Homme'), ('X', 'Accessoires Femme'), ('A', 'Vêtements Homme'), ('B', 'Vêtements Femme'), ('O', 'Autre')], default='', max_length=1),
        ),
    ]
